### PR TITLE
snake_case -> camelCase

### PR DESCRIPTION
**Pull request by lpil**

### CODE REVIEW

**Comment by j14159** [comment]
Thanks for this!  Would you like this merged pre- or post- PR #6 ?

**Comment by lpil** [comment]
Whichever you prefer. Perhaps this one first if that one is waiting for feedback.

I'm happy to resolve any conflicts so doesn't make any difference to me. :)

**Comment by lpil** [comment]
Whichever you prefer. Perhaps this one first if that one is waiting for feedback.

I'm happy to resolve any conflicts so doesn't make any difference to me. :)

**Comment by lpil** [comment]
Good to go? :)

**Comment by j14159** [comment]
@lpil good to go once conflicts resolved (merged your other option PR :) )

**Comment by lpil** [comment]
@j14159 Rebased!

**Comment by j14159** [comment]
Thanks!

**Pull request merged**
